services:

  db:
    image: kabbilkarthi/mysql-portfolio:1.1
    secrets:
      - db_root_pass
      - db_user
      - db_pass
      - db_name
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - portfolio_net
    deploy:
      placement:
        constraints:
          - node.role == manager

  web:
    image: kabbilkarthi/flask-portfolio:1.3
    ports:
      - "5000:5000"
    secrets:
      - db_root_pass
      - db_user
      - db_pass
      - db_name
    networks:
      - portfolio_net
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first      

networks:
  portfolio_net:
    external: true

volumes:
  db_data:

secrets:
  db_root_pass:
    external: true
  db_user:
    external: true
  db_pass:
    external: true
  db_name:
    external: true

